---
name: CI

on: push

jobs:
  build:
    name: Build
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - uses: bahmutov/npm-install@v1
      - name: Run tests
        run: |
        export YANDEX_API_KEY="${{ secrets.YANDEX_API_KEY }}"
        npm test
