---
name: README Lint

on:
  push:
    paths:
      - 'README.md'
      - '!node_modules/**'

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - uses: max/awesome-lint@v2.0.0
