---
name: Translation (master)

on: push

jobs:
  translation:
    name: Run translation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: fabasoad/translation-action@master
        id: translation
        with:
          provider: yandex
          api_key: "${{ secrets.YANDEX_API_KEY }}"
          lang: 'en-sl'
          source: 'This is awesome project! Thank you.'
      - name: Print translation result
        run: echo "${{ steps.translation.outputs.text }}"
