---
name: YAML Lint

on:
  push:
    paths:
      - '**.yml'
      - '!node_modules/**'

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: ibiqlik/action-yamllint@v1.0.0
        with:
          config_file: .yamllint.yml
          strict: false
          file_or_dir: action.yml .github/**.yml
